module.exports = {
  Rub21: true,
  ediyes: true,
  RichRico: true,
  Luis36995: true,
  dannykath: true,
  andygol: true,
  ruthmaben: true,
  abel801: true,
  samely: true,
  calfarome: true,
  srividya_c: true,
  PlaneMad: true,
  karitotp: true,
  lxbarth: true,
  Chetan_Gowda: true,
  ramyaragupathy: true,
  pratikyadav: true,
  jinalfolia: true,
  aarthy: true,
  oini: true,
  Jothirnadh: true,
  nikhilprabhakar: true,
  manings: true,
  saikabhi: true,
};